version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: book_php
    ports:
      - "8080:80"
    volumes:
      - ./database:/data
      - ./:/var/www/html
      - ./server/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - sqlite

  sqlite:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
        - ./database:/data
    command: tail -f /dev/null
    container_name: sqlite

